name: Curriculum Branch Sync
on:
  push:
    branches:
      - curriculum
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Sync Branches
      uses: learn-co-curriculum/curriculum-branch-sync-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
