name: Python package

on:
  push:
    branches:
      - curriculum

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure Github Credentials
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config github.token $GITHUB_TOKEN
        git config user.name $GITHUB_ACTOR
        git remote set-url origin https://learn-co-curriculum:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    - name: Create Master and Solution
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python alex.py
